In [1]:
keyy={'a': 0, 'c': 2, 'b': 1, 'e': 4, 'd': 3, 'g': 6, 'f': 5, 'i': 8, 'h': 7, 'k': 10, 'j': 9, 'm': 12, 'l': 11, 'o': 14, 'n': 13, 'q': 16, 'p': 15, 's': 18, 'r': 17, 'u': 20, 't': 19, 'w': 22, 'v': 21, 'y': 24, 'x': 23, 'z': 25, }

In [11]:
pt=input("enter the plain text use lower case: ")

enter the plain text use lower case: vuy


In [16]:
a=len(pt)

In [17]:
txt=[]
for i in pt:
    txt.append(keyy[i]) 


In [5]:
import random
aa=[]

while 1:
    b=random.randint(1,16)
    if b not in aa:
        aa.append(b)
    if len(aa)==(a*a):
        break

In [6]:
listy = [[] for i in range(a)]
c=0
for m in range(a): 
    
    for n in range(a):
        listy[m].append(aa[c])
        c+=1 
        if c == len(aa):
             break
print(listy)  

[[15, 14, 6], [7, 1, 16], [11, 5, 8]]


In [37]:
cols = (a) 
ary = [0 for i in range(cols)]   
for i in range(len(listy)):
    for j in range(len(txt)):
        ary[j] += (listy[i][j] * txt[j] )  
anss = [0 for i in range(cols)] 
for ii in range (a):
    anss[ii] +=ary[ii]%26
print(anss)         


[17, 10, 18]


In [20]:
ans = [0 for i in range(cols)] 

In [26]:
# list out keys and values separately 
key_list = list(keyy.keys()) 
val_list = list(keyy.values()) 
for jj in anss:  
     print(key_list[val_list.index(jj)]) 

  


r
k
s


#decryption

In [27]:
import numpy as np
m = np.array(listy)
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[15 14  6]
 [ 7  1 16]
 [11  5  8]]
Inverse of the said matrix:
[[-0.09677419 -0.11021505  0.29301075]
 [ 0.16129032  0.07258065 -0.26612903]
 [ 0.03225806  0.1061828  -0.11155914]]


In [35]:
mat=result.tolist()
print(mat)

rows, cols = (a,a) 
dky = [[0 for i in range(cols)] for j in range(rows)]  
for i in range(a):
    print(i)
    for j in range(a):
        dky[i][j] += (mat[i][j] % 26 ) 
print(dky)        

0
1
2
[[25.903225806451612, 25.88978494623656, 0.2930107526881721], [0.16129032258064518, 0.07258064516129033, 25.733870967741936], [0.03225806451612904, 0.10618279569892473, 25.888440860215052]]


In [39]:
et=input("Enter the encrypted message")

Enter the encrypted messagerks


In [40]:
dtxt=[]
for i in pt:
    dtxt.append(keyy[i]) 

In [42]:
cols = (a) 
aryy = [0 for i in range(cols)]   
for i in range(len(dky)):
    for j in range(len(dtxt)):
        aryy[j] += (dky[i][j] * dtxt[j] )  
danss = [0 for i in range(cols)] 
for ii in range (a):
    danss[ii] +=ary[ii]%26
print(danss) 

[0, 0, 0]
